### ISSUE TITLE
Mimic OMOP Common Data Model

### ISSUE THREAD

**Issue by MiteshP0** [MIT-LCP/mimic-omop#36]
Hello, 

I am an undergraduate student at Texas A&M University, and I have gotten access to the MIMIC III database and have set up the database with postgres. We are working on a senior design project that will involve this database, however we must convert this database into a common data model. The OMOP data model seems ideal as there is already work on it by you guys so we are hoping to get permission to use this github.

I have seen the scripts that are on this github, but I have no clue as to what needs to be done first to get the data model converted to the OMOP model. I was hoping for further documentation on how all of this works, or for one of the contributors to help point me in the right direction. Otherwise, I would have to analyze this github, which will take some time for me as I am unfamiliar with a few things like etl, and R.

Thanks!

**Comment by parisni** [comment]
Hi,

You should be able to run the etl on your side. Please give me few days to describe the process.
Building  your own pipeline from this would not be a fantastic idea.

**Comment by alistairewj** [comment]
I'd tend to agree - why do you need a common data model for such a short project? Have you seen https://github.com/MIT-LCP/mimic-code ?

**Comment by MiteshP0** [comment]
Essentially we want the CDM in order to have a more organized model for our project. Therefore, if we attempt to look for how many patients are in ICU, we just want to go to one table to do that. I feel as if the OMOP model helps standardize the current Mimic data. Ideally, by just observing the GitHub, we would love to have the tables under: mimic-omop/etl/StandardizedClinicalDataTables/ as a basis for our CDM.

**Comment by alistairewj** [comment]
There's nothing inherently easier about using the OMOP model when compared to MIMIC's current data model. In fact I would say it is a great deal more difficult because many clinically relevant concepts do not exist in the OMOP model at the moment. I would advise you to review the MIMIC documentation, the code repository, and just use the current MIMIC data model as is. This OMOP conversion is still underway and using an experimental ETL as the basis of your project is probably a bad idea.
